name: compile-latex

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build AFU document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./afu_tech.tex
